config/routes.rb
Rails.application.routes.draw do
  
  root 'boards#home'
  
  resources :boards do
    resources :songs
  end

  scope 'songs/:song_id', as: 'song' do
    resources :artists
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :song
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :board
  has_one :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_song, only: [:show]


  private
  def set_song  
    @song = Song.find(params[:song_id])
  end

  def artist_params
    params.require(:artist).permit(:name, :song_id)
  end  

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show]
  
  def index
    @boards = Board.all 
    
  end

  def show
  end
  
  private
  def set_board
    @board = Board.find(params[:id])
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_board
  before_action :set_song, only: [:show]
  
  def index
    @songs = @board.songs.limit(10)
  end

  def show
  end

  def new
    @song = @board.songs.new
  end

  private
  def song_params
    params.require(:song).permit(:name)
  end

  def set_board
    @board = Board.find(params[:board_id])
  end

  def set_song
    @song = Song.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/boards/home.html.erb
<div class="main" style='background-image: url("https://blog.studocu.com/wp-content/uploads/2017/08/best-books-book-youll-ever-read.jpg")'>

  <br />

  <h1 class="head">Welcome to the Bookboards</h1>

  <button class="ui button"><%= link_to 'View the Charts', boards_path %></button>

</div>

app/views/boards/index.html.erb
<br />
<div class="ui container">

<h1 class="ui header center aligned">All Bookboards</h1>

  <div class="ui divider"></div>

  <div class="ui grid">
    <% @boards.each do |board| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui raised link card">
    
        <%= link_to board.name, board_songs_path(board) %>

      </div>
    </div>    
    <% end %>
  </div>    

</div>

app/views/boards/new.html.erb
<h1>Board#new</h1>
<p>Find me in app/views/board/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="ui container">
      <%= yield %>
    </div>  
  </body>
</html>

app/views/songs/index.html.erb
<% @rank=0 %>

<br />
<div class="ui container">

<h1 class="ui header center aligned"><%= @board.name %></h1>

<div class="ui divider"></div>

  <table class="ui celled padded table">
    <thead>
      <tr><th class="single line">Rank</th>
      <th>Book</th>
      <th>Author</th>
    </tr></thead>
    <tbody>
      <% @songs.each do |song| %>
      <% @rank += 1 %>
      <tr>
        <td>
          <h2 class="ui center aligned header"><%= @rank %></h2>
        </td>
        <td class="single line">
          <%= song.name %>
        </td>
        <td class="single line">
          <%= song.artist.name %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <button class="ui button">
    <%= link_to 'Back to bookboards', boards_path(@board) %>
  </button>


</div>  

app/views/songs/new.html.erb
<h1>Song#new</h1>
<p>Find me in app/views/song/new.html.erb</p>

app/views/songs/show.html.erb
<h1><%= @board.name %> - <%= @song.name %></h1>

<% @song.each do |song| %>
<% end %>